export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_RESET_SUCCESS = "AUTH_RESET_SUCCESS";
export const AUTH_DISMISS_ERROR = "AUTH_DISMISS_ERROR";
export const AUTH_SET_OOBCODE = "AUTH_SET_OOBCODE";